@startuml

!define table(x) entity x << (T, white) >>
!define primary_key(x) <b><&key> x</b>
!define column(x) <&media-record> x
!define foreign_key(x) <&key> x

table( Accessory ) {
  primary_key( id ) : int
  column( name ) : string 
  column( controlDate ) : DateTimeInterface 
  column( detector ) : bool 
}

table( Container ) {
  primary_key( id ) : int
  column( serialNumber ) : string 
  column( capacity ) : float 
  column( fluidQuantity ) : float 
  foreign_key( fluid ) : Fluid <<FK>>
}

table( Equipment ) {
  primary_key( id ) : int
  column( name ) : string 
  column( weight ) : float 
  column( co2EqTonnage ) : float 
  column( leakDetectionSystem ) : bool 
  column( controlFrequency ) : int 
  foreign_key( fluid ) : Fluid <<FK>>
}

table( Fluid ) {
  primary_key( id ) : int
  column( name ) : string 
  foreign_key( fluidType ) : FluidType <<FK>>
}

table( FluidType ) {
  primary_key( id ) : int
  column( name ) : string 
  column( flammable ) : bool 
}

table( Group ) {
  primary_key( id ) : int
  column( name ) : string 
}

table( Intervention ) {
  primary_key( id ) : int
  column( date ) : DateTimeInterface 
  column( virginFluidQuantity ) : float 
  column( recycledFluidQuantity ) : float 
  column( regeneratedFluidQuantity ) : float 
  column( forProcessingFluidQuantity ) : float 
  column( bsffNumber ) : string 
  column( reusableFluidQuantity ) : float 
  column( collectedFluidDestination ) : string 
  column( remarks ) : string 
  foreign_key( interventionType ) : InterventionType <<FK>>
  column( otherInterventionType ) : string 
  column( leaks ) : bool 
  foreign_key( equipment ) : Equipment <<FK>>
  foreign_key( container ) : Container <<FK>>
  foreign_key( accessory ) : Accessory <<FK>>
  foreign_key( user ) : User <<FK>>
  column( pdfPath ) : string 
}

table( InterventionType ) {
  primary_key( id ) : int
  column( name ) : string 
}

table( Leakage ) {
  primary_key( id ) : int
  column( num ) : int 
  column( count ) : int 
  column( location ) : string 
  column( fixed ) : bool 
  foreign_key( intervention ) : Intervention <<FK>>
}

table( Parameter ) {
  primary_key( id ) : int
  column( parameter ) : string 
  column( value ) : string 
}

table( User ) {
  primary_key( id ) : int
  column( userId ) : string UNIQUE
  column( roles ) : json 
  column( password ) : string 
  column( firstName ) : string 
  column( lastName ) : string 
  foreign_key( userGroup ) : Group <<FK>>
}

Container "*" -- "1" Fluid
Equipment "*" -- "1" Fluid
Fluid "*" -- "1" FluidType
Intervention "*" -- "1" InterventionType
Intervention "*" -- "1" Equipment
Intervention "*" -- "1" Container
Intervention "*" -- "1" Accessory
Intervention "*" -- "1" User
Leakage "*" -- "1" Intervention
User "*" -- "1" Group

@enduml
